seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
image_size: 1536
batch_size: 4
num_workers: 8
lr: 0.0003
model_name: efficientnet-b1
in_channels: 3
classes: 1
min_lr: 3e-06
epochs: 20
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/efficientnet-b1_baseline_gray_scale_stack_images