batch_size: 8
classes: 2
epochs: 30
gradient_accumulation_steps: 1
in_channels: 1
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
labels_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_3_dense_full_self_encode.csv
lr: 5e-04
min_lr: 3e-05
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/seresnext50_multiview_30_epoch_5e_04_dice_loss_normalize_hflip_attention_unet
model_name: tu-timm/seresnext50_32x4d.gluon_in1k
num_workers: 4
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense
