seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
image_size: 1536
batch_size: 2
num_workers: 8
lr: 0.00015
model_name: tu-timm/tf_efficientnet_b5.ns_jft_in1k
in_channels: 3
classes: 2
min_lr: 3e-06
epochs: 15
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/tf_efficientnet_b5_pad_kidney_multiview
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv