seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
image_size: 1536
batch_size: 8
num_workers: 16
lr: 0.0003
model_name: tu-seresnext26d_32x4d
in_channels: 3
classes: 1
min_lr: 3e-06
epochs: 15
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/seresnext26d_32x4d_pad_if_needed_flips