batch_size: 2
classes: 2
epochs: 25
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
lr: 3e-04
min_lr: 3e-06
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/maxvit_small_tf_384_multiview
model_name: tu-timm/maxvit_small_tf_384.in1k
num_workers: 8
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
validation_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_3_dense_full.csv
gradient_accumulation_steps: 2