batch_size: 4
classes: 2
epochs: 15
gradient_accumulation_steps: 1
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
lr: 5e-04
min_lr: 3e-06
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/nextvit_base_multiview_15_epoch_5e_04_dice_loss
model_name: nextvit_base
num_workers: 4
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
