batch_size: 4
classes: 2
epochs: 15
gradient_accumulation_steps: 1
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
labels_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_3_dense_full_self_encode.csv
lr: 5e-04
min_lr: 3e-05
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/dm_nfnet_f1_volume_normalize_dice_find_best_epoch
model_name: tu-timm/dm_nfnet_f1.dm_in1k
num_workers: 4
pad_factor: 32
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense

