batch_size: 4
classes: 2
epochs: 5
gradient_accumulation_steps: 1
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
labels_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_3_dense_full_self_encode.csv
lr: 5e-04
min_lr: 3e-05
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/maxvit_base_tf_224_volume_normalize_dice_kidney_3_sparse_all
model_name: tu-timm/maxvit_base_tf_224.in1k
num_workers: 4
pad_factor: 224
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense
