batch_size: 4
classes: 1
epochs: 15
gradient_accumulation_steps: 1
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
labels_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_2_solution.csv
lr: 5e-04
min_lr: 3e-05
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/upernet_swin_base_lr_scheduler_no_kidney_224
model_name: openmmlab/upernet-swin-base
num_workers: 2
pad_factor: 224
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
pseudo_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_5