batch_size: 2
classes: 2
epochs: 15
gradient_accumulation_steps: 1
in_channels: 3
kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
labels_df: /home/mithil/PycharmProjects/SenNetKideny/data/kidney_3_dense_full_self_encode.csv
lr: 2.5e-04
min_lr: 1.5e-05
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/nextvit_base_volume_normalize_dice_find_best_epoch
model_name: nextvit_base
num_workers: 4
pad_factor: 32
seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_sparse
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense

