seed: 42
train_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_1_dense
train_dir_2: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_2
validation_dir: /home/mithil/PycharmProjects/SenNetKideny/data/train/kidney_3_dense
batch_size: 4
num_workers: 4
lr: 0.00025
model_name: tu-timm/maxvit_small_tf_384.in1k
in_channels: 3
classes: 2
min_lr: 3e-06
epochs: 15
model_dir: /home/mithil/PycharmProjects/SenNetKideny/models/maxvit_small_tf_multiview_15_epoch_5e_04

kidneys_df: /home/mithil/PycharmProjects/SenNetKideny/data/train_rles_kidneys.csv
gradient_accumulation_steps: 1